### ISSUE TITLE
Make default VM size as Small (1 cores, 1792 MB)

### ISSUE THREAD

**Issue by avranju** [MSOpenTech/msopentech-tools-for-intellij#118]
Make the default VM size as Small (1 cores, 1792 MB) instead of "Basic A0".

**Comment by kasturiswain** [comment]
Now the default VM size is showing as Medium(2 cores,3584 MB) instead of "Basic A0".

**Comment by akrakovsky** [comment]
The default VM size is now being set by the recommended size by the VM image. Not all the VMs have this value setted so the default in that case should be Small. This was done in order to match Visual Studio behavior. I've been testing, and so far, the recommended size is matching in IntelliJ and Visual Studio for the same image.

**Comment by kasturiswain** [comment]
As per the above design the above issue is fixed and the functionality is working as expected in the latest build.
