### ISSUE TITLE
Plugin throwing exception when user trying to add entity twice of a created table

### ISSUE THREAD

**Issue by kasturiswain** [MSOpenTech/msopentech-tools-for-intellij#267]
<b>Environment: </b>Windows/IntelliJ14

Sign in Subscription.
Click Azure.
Click storage.
Expand a Storage Account.
Expand a particular Storage.
Expand tables.
click on the '+' icon to add entity.
click again the same icon.
It is throwing the below exception.
![exception](https://cloud.githubusercontent.com/assets/10046647/7294994/c64ad45c-e9cf-11e4-849b-8b4abd794362.png)

**Comment by akrakovsky** [comment]
I can't reproduce this issue as you describe it. Are you clicking twice on the button before the dialogs shows, or are you clicking once, creating an entity, and then clicking again and creating a second one?

**Comment by kasturiswain** [comment]
clicking once, creating an entity, and then clicking again and creating a second one. (do not give any value for the partition key or row key)

**Comment by akrakovsky** [comment]
Ok, the problem seems to be that the pair of values of the partition key and the row key must be unique for the table. Since blanks are valid values for the keys, the error is shown because there is already an entity with those partition key and row key pair. 

I'm thinking of adding a validation and a more descriptive error message when an entity with an already created key pair is about to be created.

**Comment by BeatriceOltean** [comment]
To add descriptive error message when an entity with an already created key pair is about to be created

**Comment by BeatriceOltean** [comment]
Need error message

**Comment by kasturiswain** [comment]
This issue is fixed and functionality is working as expected in the latest build.
