### ISSUE TITLE
Not able to configure and add azure service activity and o 365 activity to the project[PluginSplit]

### ISSUE THREAD

**Issue by ramkumargtv** [MSOpenTech/msopentech-tools-for-intellij#379]
Environment:</b>
OS - Windows
Plugin Version -Azure Tools for Java Developers for Intellij Version 1.0
IDE - Intellij 14.1.4 , JRE 1.8
Authentication - AD Sign-in

Steps</b>
Create a project.
Try to add azure activity and O 365 activity .
It will pop up a dialog box as attached in which azure services cannot be configured properly.

In case of Azure Service Activity
![6c767eba-1916-11e5-9d3e-c4c78c581472](https://cloud.githubusercontent.com/assets/11503573/9634411/298667ac-5181-11e5-9275-e473f7bcec4c.png)
In Case of Office 365 activity
![unnn](https://cloud.githubusercontent.com/assets/11503573/9634431/3b7e5c1c-5181-11e5-859c-ff4a719ce538.png)

**Comment by akrakovsky** [comment]
This problem seems to be related to a known consequence of the way we are adding the templates.

When an android project is created with the Microsoft Cloud Service for Android, the templates are copied into the project. If the plugin is removed, the templates are not removed from the project, and they will be still accessible (for that particular project). Since the code needed to configure the Azure services is contained in the plugin, and the plugin was removed, the field is shown as a textbox by default. 

Unfortunately, the Open API framework doesn't provide install and uninstall events for plugins, witch would allow us to patch this.

**Comment by ramkumargtv** [comment]
Couldn't triage this issue , due to issue #380

**Comment by ramkumargtv** [comment]
Not reproducible now in latest build .
