### ISSUE TITLE
Mobile service with a .NET backend produces error in service explorer

### ISSUE THREAD

**Issue by avranju** [MSOpenTech/msopentech-tools-for-intellij#64]
If you have a mobile service which uses a .NET backend in your subscription then the service explorer produces the following error:

![err](https://cloud.githubusercontent.com/assets/628128/5536855/480a8614-8a4d-11e4-8706-7948291403d5.png)

**Comment by BeatriceOltean** [comment]
We should disable this for .Net, It is unsupported. No child item should be added in the tree

**Comment by babumuralidharan** [comment]
This is working as expected. Currently the respective mobile service is shown in service explorer but nothing underneath. Also when you right click the respective mobile service we could see the warning in the service log. Still we can use this mobile service when we add an azure service activity but not sure if user can do any customization on the template generated code since we do not support .net backend. @avranju thoughts??

**Comment by avranju** [comment]
We don't support a .NET backend for the mobile service in service explorer but I'd imagine that Android apps should be able to make use of a .NET backend based mobile service.
