### ISSUE TITLE
Shut down button is enabled even if user has clicked the same

### ISSUE THREAD

**Issue by kasturiswain** [MSOpenTech/msopentech-tools-for-intellij#88]
When shut down button is clicked and the system is not yet shut down,the plugin should not allow the user to shut down the system again.
In Azure portal the shut down button is disabled after the user clicks shut down button.
PFB the screen shot.
![shutdownplugin](https://cloud.githubusercontent.com/assets/10046647/5718929/dfe26d34-9b38-11e4-90c1-2f231a25e561.png)
![shutdownazureportal](https://cloud.githubusercontent.com/assets/10046647/5718942/0bccd88a-9b39-11e4-820e-3a98b820c02b.png)

**Comment by akrakovsky** [comment]
Blocked by issue #94

**Comment by kasturiswain** [comment]
In azure portal when we click on "shut down", connect and delete options are enabled.
PFB the screen shot.
![88 1](https://cloud.githubusercontent.com/assets/10046647/5753297/acab2c88-9cac-11e4-8286-0b22147ff5ca.png)

In plug in when we click on "shut down", none of the option is enabled.
PFB the screen shot.
![88](https://cloud.githubusercontent.com/assets/10046647/5753299/cdcdeacc-9cac-11e4-9403-b769384b0eab.png)

**Comment by avranju** [comment]
This is by design. For now, let's go ahead with the current implementation. Visual Studio also has a similar behavior in that it disables all commands on the node while an operation is pending except for the "Refresh" command. We can take up a new item to investigate implementing that. @kasturiswain, please close this issue if there isn't anything else open here.

**Comment by kasturiswain** [comment]
In this case when we click on any activity (like start, shut down, restart) it disables all the activities.
As per the current design this is working as expected.
